services:
  accounts:
    image: "jayadurga332k/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - avobank
  cards:
    image: "jayadurga332k/cards:v1"
    container_name: cards-ms
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - avobank
  loans:
    image: "jayadurga332k/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - avobank
networks:
  avobank:
    driver: "bridge"